input_path = 'examples\sample.mzML'
output_path = 'examples\viridis_output.csv'
output_format = "Csv"
ms1_similarity_metrics = ["cosine"]
ms2_similarity_metrics = ["cosine", "modified-cosine"]
ms1_minimum_intensity = 10000.0
ms2_minimum_intensity = 2000.0
noise_threshold = 100
mass_tolerance = 0.01
heatmap_enabled = true
image_path = 'examples\viridis_output.png'
image_format = "Png"

[theme.background]
r = 20
g = 20
b = 20

[theme.low]
r = 68
g = 1
b = 84

[theme.high]
r = 253
g = 231
b = 37
