input_path = 'C:\Users\nbrit\Desktop\Rust Practice\pass-cli\tests\data\FeatureFinderMetaboIdent_1_input.mzML'
output_path = "output.csv"
output_format = "Csv"
ms1_similarity_metrics = ["cosine"]
ms2_similarity_metrics = ["cosine", "modified-cosine"]
ms1_minimum_intensity = 1.0
ms2_minimum_intensity = 0.0
noise_threshold = 100
mass_tolerance = 0.01
heatmap_enabled = true
image_path = "similarity_heatmap.png"
image_format = "Png"

[theme.background]
r = 255
g = 255
b = 255

[theme.low]
r = 255
g = 255
b = 255

[theme.high]
r = 0
g = 0
b = 255
